title: "Welcome To Pradise!" # name of the site
author: Siavash Khalvati # name of site's author
  #url: http://ciavash.info # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  Dabbling with life

permalink: /:slug.html

favicon: "favicon.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

  #remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page
 # lowercase_titles: true # show titles in lowercase in lists

author:
  name: Siavash Khalvati
  email: "s.khalvati@gmail.com"
  github: Binariography 
  linkedin: siavash-khalvati-75a865b6


footer-links-active:
  rss: false
  facebook: false
  email: true
  twitter: false
  google-plus: false
  github: true
  reddit: false
  linkedin: true
  xing: false
  stackoverflow: false
  snapchat: false
  instagram: false
  youtube: false
  spotify: false
  telephone: false


sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jektex
